language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  - SECRET=CXLntS#roUdF8jJoaEx#2N9rRH8gKF%C
install:
  - npm install
script:
  - echo Running Eslint in main path
  - npm run eslint-src
  - echo Running Eslint in tests
  - npm run eslint-test
  - echo Testing controllers
  - npm run test-controllers