language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - echo Running Eslint in main path
  - npm run eslint-script
  - echo Running Eslint in tests
  - npm run eslint-test
  - echo Testing controllers
  - npm run test-controllers